### ISSUE TITLE
Rewrite "Implementing Vec" chapter - Unique is permanently unstable 

### ISSUE THREAD

**Issue by tesuji** [rust-lang/nomicon#160] opened 2019-08-24 12:39 UTC
This chapter use `Unique` to demonstrate how to implement a Vec. But it is
permanently unstable and can only be used by std. Also in
https://github.com/rust-lang/rust/blob/478464570e60523adc6d303577d1782229ca1f93/src/libcore/ptr/unique.rs#L28-L34
it recommends that we should use `NonNull` instead and consider `PhantomData<T>`.

**Comment by eisterman** [comment] 2020-01-05 20:15
What is the pattern to use instead of Unique? With NonNull?

**Comment by Coder-256** [comment] 2020-02-02 03:25
I think this is a duplicate of #83.

**Closed** 2021-05-02 08:41 UTC
