### ISSUE TITLE
Nomicon and Reference duplicated effort 

### ISSUE THREAD

**Issue by OnlyLys** [rust-lang/nomicon#230] opened 2020-07-17 03:08 UTC
Hi, I noticed that a few sections within the nomicon overlap with that of the reference. 

For instance, coercions:

- https://doc.rust-lang.org/reference/type-coercions.html#type-coercions
- https://doc.rust-lang.org/nomicon/coercions.html?#coercions

and the method call operator:

https://doc.rust-lang.org/reference/expressions/method-call-expr.html?#method-call-expressions
https://doc.rust-lang.org/nomicon/dot-operator.html

Are these sections still necessary in the nomicon?

**Comment by cuviper** [comment] 2020-08-12 19:04
Another one is "Subtyping and Variance", which was added to the reference in https://github.com/rust-lang/reference/pull/186.

- https://doc.rust-lang.org/reference/subtyping.html
- https://doc.rust-lang.org/nomicon/subtyping.html

The reference chapter is shorter, but it also mentions the variance of `Trait<T> + 'a`, which is missing from the nomicon.

**Comment by JohnTitor** [comment] 2021-06-10 03:18
Discussed on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/237824-t-lang.2Fdoc/topic/Duplicated.20efforts.20between.20the.20nomicon.20and.20the.20reference) a bit, @ehuss pointed out:

>  I would probably defer the list of rules (like the coercions and casts) to the reference, and keep the nomicon focused on the discussion of how to use those effectively and what the implications can be.
>
> In theory that information could be duplicated, but given our limited resources, I think it is very easy for them to go out of sync.

Focusing on the good usage makes sense to me. The problem is that the coercions and method call operator chapter don't show any good usage currently, we should improve them anyway.

**Comment by JohnTitor** [comment] 2021-08-30 22:38
I'm going to close this issue in favor of #279 (and some of them have been resolved). Thanks for the report!

**Closed by JohnTitor** 2021-08-30 22:38 UTC
Labels: C-meta
